name: Build, Test, Slim, and Publish Application

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
          cache-dependency-path: |
            **/go.sum

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx

      - name: Install DockerSlim
        run: |
          curl -sL https://downloads.dockerslim.com/install.sh | sudo bash
          export PATH=$PATH:$HOME/.docker-slim/bin

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Tests
        run: go test ./... -v -coverprofile=coverage.out

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -extldflags '-static'" -o main ./cmd/app/main.go
          upx --ultra-brute --lzma main

      - name: Build Docker Image
        run: |
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/gin-app:${{ github.ref_name }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Slim Docker Image
        run: |
          $HOME/.docker-slim/bin/docker-slim build --tag docker.io/${{ secrets.DOCKER_USERNAME }}/gin-app-slim:${{ github.ref_name }} docker.io/${{ secrets.DOCKER_USERNAME }}/gin-app:${{ github.ref_name }}

      - name: Push Slimmed Docker Image
        run: |
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/gin-app-slim:${{ github.ref_name }}
