name: Build, Test, and Publish Application

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
          cache-dependency-path: |
            **/go.sum

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Tests
        run: |
          mkdir -p coverage
          go test ./... -v -coverprofile=coverage/coverage.out -json > coverage/test-report.json

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o app .

      - name: Build Docker Image
        run: |
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/gin-app:${{ github.ref_name }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/gin-app:${{ github.ref_name }}
